import CONSTANTS from './constants';

const CONFIGS = {
  CONTACTS_FILTER_DEFAULT_VALUES: {
    IS_FAVOURITE: CONSTANTS.CONTACTS_FILTER_OPTIONS[0].value,
    FULL_NAME: '',
  },
  CONTACTS_ORDER_DEFAULT_VALUE: {
    BY_NAME: CONSTANTS.ORDER.ASC,
  },
};

export default CONFIGS;
